# Generated by Django 3.1.13 on 2021-10-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20211018_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
